export default {
  homeReducer: {
    WILL_LOAD_STAT: 'WILL_LOAD_STAT',
    LOAD_STAT: 'LOAD_STAT',
    LOAD_STAT_FAILED: 'LOAD_STAT_FAILED',
  },
  appReducer: {
    LOAD_BOOT_STAGE: 'LOAD_BOOT_STAGE',
    APP_BOOTUP_FAILED: 'APP_BOOTUP_FAILED',
    APP_BOOTUP_SUCCESS: 'APP_BOOTUP_SUCCESS',
    APP_UPDATE_REQUIRED: 'APP_UPDATE_REQUIRED',
    SKIP_UPDATE: 'SKIP_UPDATE',
    START_NETWORK_CALL: 'START_NETWORK_CALL',
    STOP_NETWORK_CALL: 'STOP_NETWORK_CALL',
    DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR',
  },
};
